# docker-compose.yml をベースに開発用に設定を追加、上書き

services:
  # database
  database:
    env_file:
      - ./backend/.env

  # backend
  backend:
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/app:/code/app
      - ./backend/.env:/code/.env
      - ./backend/manage.py:/code/manage.py
      - ./backend/requirements.txt:/code/requirements.txt
    depends_on:
      database:
        condition: service_healthy

  # frontend
  frontend:
    volumes:
      - ./frontend/app:/app
